### PR TITLE
Release 0.4.0

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary

Merge release 0.4.0 into develop. This release includes Tone Analyzer, Tradeoff Analytics, Conversation and Visual Recognition abstractions.

### CODE REVIEW

**Comment by mediumTaj** [comment]
@germanattanasio Ready to release 0.4.0! Can you take a look to see if I'm missing anything?

**Comment by mediumTaj** [comment]
@germanattanasio ok... now really ready

**Comment by germanattanasio** [comment]
I can't review 281 files haha but I can give you a list of items that should be included here:
- [ ] README updated with the new services
- [ ] Tests for the new services
- [ ] CHANGELOG updated
- [ ] Examples for the new services
- [ ] Removed the old/deprecated services from README and `Examples` folder

**Comment by mediumTaj** [comment]
Heh yes perfect!

**Pull request merged**
