### PR TITLE
Gh279 streaming example

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary

Update Speech to Text streaming example

### CODE REVIEW

**Comment by kimberlysiva** [comment]
@mediumTaj Just noticed that the maxLevel logic was reverted again. Both streaming samples need to be updated to use `Mathf.Max(Mathf.Abs(Mathf.Min(samples)), Mathf.Max(samples))`

**Comment by kimberlysiva** [comment]
@mediumTaj Also, we lost the change to `_sendEvent.WaitOne(50);` instead of 500.

**Comment by mediumTaj** [comment]
good catches, thanks!

**Comment by mediumTaj** [comment]
@kimberlysiva I'm planning to merge this PR in today - if you have some time can you review it and let me know if we are missing anything?

**Comment by kimberlysiva** [comment]
@mediumTaj I've been testing it today and things look good (also on Hololens, very responsive!)

I think we may want to rename `ExampleStreamingChunked`, since at first glance this suggests a REST connection with chunked encoding.

**Comment by mediumTaj** [comment]
Awesome thanks! Chunked rename is done and pushed. After we pass CI, I'll merge this in.

**Pull request merged**
