### PR TITLE
UnityWebRequest

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary
This pull request removes dependency on the `WWW` library in favor of `UnityWebRequest`. An option to disable SSL verification was added for compatibility with IBM Cloud Private. Finally each method now has the httpmethod explicitly set.

Note: We still need to test this on IBM Cloud Private before merging.

### CODE REVIEW

**Comment by mediumTaj** [comment]
@kimberlysiva Can you take a look at this PR when you get a chance and let me know if it breaks anything in Lexicon?

**Comment by kimberlysiva** [comment]
@mediumTaj Sorry for the long delay. The first problem I'm having is that the error code isn't parsed correctly (Unity 2017.4.1f1). For example:

```
URL: https://stream.watsonplatform.net/speech-to-text/api/v1/customizations/f3d1f62f-b5a9-45da-8435-6176a19c4256/corpora/Lexicon_Sample_Intents?allow_overwrite=True,
ErrorCode: 0,
Error: Generic/unknown HTTP error,
Response: {
   "code": 409,
   "code_description": "Conflict",
   "error": "Customization 'f3d1f62f-b5a9-45da-8435-6176a19c4256' is currently locked to process your last request."
}
```

Note the code in the Response is 409, but the parsed ErrorCode is 0.

**Comment by mediumTaj** [comment]
Thanks Kimberly, I updated this!

**Comment by kimberlysiva** [comment]
Getting an error for UWP (HoloLens) with the .NET Scripting Backend:

`Assets\unity-sdk-4191-unity-web-request\Scripts\Logging\Logger.cs(227,17): error CS0234: The type or namespace name 'Console' does not exist in the namespace 'System' (are you missing an assembly reference?)`

**Pull request merged**
