### PR TITLE
Example Streaming to Assistant & Better parsing of MessageResponse

### PR DESCRIPTION
**Pull request by Juleffel**
Create an example for linking Speech To Text and Assistant via Events and also do a better and more clear parsing of MessageResponses

The new Example can be found under Examples/ServiceExamples/ExampleAssistant.unity.
It involves one game object (Watson) and three scripts:
- ExampleStreaming (some minor changes to raise events on recognized text)
- ExampleAssistantV1Message (which is basically a simpler version of ExampleAssistantV1 just to send messages)
- ExampleStreamingToAssistant (which get the events from ExampleStreaming and call ExampleAssistant when a message is understood).

Tests are still passing in old examples.

### CODE REVIEW

**Comment by Juleffel** [comment]
I'm actually really bad with C# so I've no idea what is better lol (that's the reason why I didn't succeed to just work with casts in the first place to get my entities out in a array...) Never mind the change on MessageResponse, then!
Although you may create another MessageResponseBasicParse just used there in order to handle the most basic parsings like in this code ? I don't know.

**Comment by mediumTaj** [comment]
Maybe I can add a helper function that returns intents, entities, etc?

**Comment by Juleffel** [comment]
Would be great ! Thanks for your work ;)

**Comment by mediumTaj** [comment]
Closing this in favor of https://github.com/watson-developer-cloud/unity-sdk/issues/477

**Pull request closed without merging**
