### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by mediumTaj**
### Summary
This pull request removes duplicate table of contents from the readme. Additionally it removes exception that Disco V2 is only for CP4D.

### CODE REVIEW

**Review by kevinkowa — APPROVED** [review]
LGTM!

**Review by SirSpidey — COMMENTED** [review]
Change here is ok. 

Grammar issue at current line 71. The Readmes don't own anything, so no `'`. Also, most folders don't have READMEs. And do those folders actually help people get started with the SDK? Doesn't seem obvious to me.

> To get started with the Watson Services in Unity, click on each service below to read through each of their `README.md`'s and their codes.

Should be something like this.
```
To get started with a Watson Service in Unity, follow the link to see the  code.
```

**Comment by mediumTaj** [comment]
Updated per suggestion, waiting for CI

**Review by SirSpidey — APPROVED** [review]
👍

**Pull request merged**
