### PR TITLE
Add support for .NET Core (Hololens)

### PR DESCRIPTION
**Pull request by kimberlysiva**
### Summary

Moved WebSocketSharp to a dll and excluded it on WSA.
Fixed all code that wouldn't compile on .Net Core. All changes are wrapped in NETFX_CORE conditional compilation checks, so nothing should change on other platforms.

### Other Information

Note that these changes will only work on Hololens with the .NET scripting backend, not IL2CPP.

Please test the WebSocketSharp dll on other platforms (e.g. iOS/Android). It is possible that platform-specific builds will need to be made. The submitted dll is built from the websocketsharp master branch as of October 12, 2017.

### CODE REVIEW

**Comment by kimberlysiva** [comment]
All unit tests passed on Hololens, logs attached.
[HololensUnitTests.txt](https://github.com/watson-developer-cloud/unity-sdk/files/1380417/HololensUnitTests.txt)

**Comment by kimberlysiva** [comment]
Here's a unitypackage that bundles up this PR with a simple Hololens sample scene. The scene tests Speech-To-Text streaming with a Hololens-friendly camera setup. The STT results are streamed to a canvas two meters in front of the user (you may need to look around a little to find the canvas).

Be sure to set your Watson Speech-to-Text username and password in StreamingTest.cs. Also be sure to enable InternetClient and Microphone under Publishing Settings/Capabilities.

Please report any issues (or successes!) here. Let us know what version of Unity you are using. Thanks!

[WatsonHololens.zip](https://github.com/watson-developer-cloud/unity-sdk/files/1419825/WatsonHololens.zip)

**Comment by mediumTaj** [comment]
@kimberlysiva I think this looks good! Everything is working as expected. I was trying to run the sample scene above on hololens but I only get the application window in the headset. I don't see the application actually starting. Is there something I'm missing?

**Comment by kimberlysiva** [comment]
Make sure you've checked "Virtual Reality Supported" under Player Settings > Other Settings. Let me know if that helps!

**Pull request merged**
