### PR TITLE
ci: Add deploy

### PR DESCRIPTION
**Pull request by Mikemosca**
[skip ci] Add github actions deploy

### Summary

Add deploy for Github actions.  Right now itas dry-run so we can test once into master

### CODE REVIEW

**Comment by mediumTaj** [comment]
Mike, I just realized this but can we do this on linux rather than osx? since we are not installing Unity we no longer have a dependency on OSX.

**Comment by Mikemosca** [comment]
> Mike, I just realized this but can we do this on linux rather than osx? since we are not installing Unity we no longer have a dependency on OSX.

Absolutely!  Done!

**Comment by Mikemosca** [comment]
I don't know why it's telling me I have not signed the CLA.  I signed it like 4 times now.

**Review by mediumTaj — APPROVED** [review]
👍 looks good!

**Pull request merged**
