### PR TITLE
Improved Error Handling

### PR DESCRIPTION
**Pull request by kimberlysiva**
As discussed in https://github.com/watson-developer-cloud/unity-sdk/issues/265

Added an Error class to RESTConnector, encapsulating the url, error code, error message, and full server response (typically json). Each service callback delegate now includes an error parameter, providing an Error object on error or null on success. Updated all unit tests and samples to use the new delegate signatures.

The only TODO is concerning the two STT streaming delegates. `OnRecognize` and `OnRecognizeSpeaker` both include the Error parameter but these are currently always null.

### CODE REVIEW

**Comment by kimberlysiva** [comment]
This also resolves potential null reference exceptions that I reported in https://github.com/watson-developer-cloud/unity-sdk/issues/265

**Comment by mediumTaj** [comment]
I think this looks good but we cannot release a breaking change until we are ready to release a new version of the SDK. I don't think we can move on that because of error handling. I think @ereneld 's suggestion is good. Or if possible do not change the delegates and if there is an error, but send a stringified error in the data string?

**Comment by ereneld** [comment]
It looks like we can have optional parameter in the delegate ? why not? due to the version of .net ? 
> https://stackoverflow.com/questions/5729154/using-c-sharp-delegates-with-methods-with-optional-parameters

`To be clear, we're never giving the user the Response object, so they can't retrieve the error string at all right now.`
=> that is a big thing. I might miss that part already. We should return response object instead of data, which is another big change if we don't have. :'(

**Comment by kimberlysiva** [comment]
@ereneld I can't seem to get it to work... Getting errors like this:

```
A method or delegate `IBM.Watson.DeveloperCloud.UnitTests.TestSpeechToText.HandleGetModels(IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.ModelSet, string)' parameters do not match delegate `IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.SpeechToText.OnGetModels(IBM.Watson.DeveloperCloud.Services.SpeechToText.v1.ModelSet, string, IBM.Watson.DeveloperCloud.Connection.RESTConnector.Error)' parameters
```

I think this explains why: https://stackoverflow.com/questions/5636218/optional-parameters-on-delegates-doesnt-work-properly

Yep, there's absolutely no way to retrieve the error right now. It's logged to the console, but that's not terribly useful if we're trying to react to specific errors...

Returning the Response object would be great! But yes, that'll require a signature change as well. The best solution would be returning the Response object with this new Error object included. I realize this is a breaking change, but some change seems required here, so we may as well get it right before the first asset store release.

I'm happy to do the grunt work of making the changes if you guys can point me in the right direction!

**Comment by kimberlysiva** [comment]
Also, just to clarify, you said:

`We should return response object instead of data`

I don't think it's an instead... We want to return the parsed data object, and we want to return any customData the user might have passes us. We ALSO want to return an error object or the full response object.

@mediumTaj what do you think?

**Comment by ereneld** [comment]
3 separate conversation. :) 
1- Optional parameter on delegate. 
I got what you are saying now. Yes, you can define optional parameter but it should be define in the implementation side as well. It won't work if you skip the parameter. This results that even if you define optional parameter yes, it won't be backward compatible. So, it won't be different then adding Error object. So, yes, we can skip this option. 
2- What to return to users? 
I prefer a response object having all custom parsed data, error object, data user passed, response data as byte array. This might a big change for now but worth to investigate. 
3- Better error handling. 
This is the PR topic. If we can brainstorm and discuss about number 2 then we can proceed this. I feel like it is a short-cut solution that we can consider to merge.

**Comment by kimberlysiva** [comment]
1) That's exactly right :)

2) We can do that, but we'll have different response types per API call (since they mostly return different data objects).

Honestly I'd love to see a simpler "template" for each API method. Right now each API call requires four methods to implement and a bit of boilerplate, perhaps this could be condensed... (generics maybe?) I recently implemented a large chunk of the Conversation customization api, and boy was it exhausting! But again, that's a bigger change, and now probably isn't the time. (Still, if you'd like me to propose a simpler "API template" I'd be happy to put something together).

I need to step away for today, but I'll rejoin this conversation tomorrow. Thanks!

**Comment by mediumTaj** [comment]
I wonder if instead of an error object if it would be better to return something more generic like a dictionary that contains the error response object and any other custom data that the user wants to pass through. It might be some work to parse the error response and convert it out but at least all the data would be there and since each service seems to have a different error response it might be useful. Thoughts?

**Comment by mediumTaj** [comment]
Actually khan mentioned something that might work pretty well. A response object that holds the response code, byte[] response data, the error object and possibly a dictionary<string, object> for any kind of user data that wants to get passed. This would require some _significant_ changes in the SDK though but it is pretty important.

**Comment by kimberlysiva** [comment]
So here's one thought on how we could organize this:

Add a new class to RESTConnector:
```
public class ParsedResponse<T> where T : new()
{
    /// <summary>
    /// True if the request was successful.
    /// </summary>
    public bool Success { get; set; }
    /// <summary>
    /// Error object if Success is false (null otherwise).
    /// </summary>
    public Error Error { get; set; }
    /// <summary>
    /// The data returned by the request.
    /// </summary>
    public byte[] Data { get; set; }
    /// <summary>
    /// The JSON representation of the data.
    /// </summary>
    public string JSON { get; set; }
    /// <summary>
    /// The parsed data object.
    /// </summary>
    public T DataObject { get; set; }
    /// <summary>
    /// Custom data the user passed with the request.
    /// </summary>
    public string CustomData { get; set; }
    /// <summary>
    /// The amount of time in seconds it took to get this response from the server.
    /// </summary>
    public float ElapsedTime { get; set; }

    /// <summary>
    /// Initializes a new instance of the ParsedResponse class.
    /// </summary>
    /// <param name="resp">The server response.</param>
    /// <param name="customData">User custom data.</param>
    /// <param name="serializer">Serializer to parse data.</param>
    public ParsedResponse(Response resp, string customData, fsSerializer serializer)
    {
        Success = resp.Success;
        Error = resp.Error;
        Data = resp.Data;
        ElapsedTime = resp.ElapsedTime;
        CustomData = customData;

        if (Success)
            Success = Parse(serializer);
    }

    private bool Parse(fsSerializer serializer)
    {
        T dataObject = new T();
        fsData data = null;

        try
        {
            fsResult r = fsJsonParser.Parse(Encoding.UTF8.GetString(Data), out data);
            if (!r.Succeeded)
                throw new WatsonException(r.FormattedMessages);

            object obj = dataObject;
            r = serializer.TryDeserialize(data, obj.GetType(), ref obj);
            if (!r.Succeeded)
                throw new WatsonException(r.FormattedMessages);

            JSON = data.ToString();
            DataObject = dataObject;
        }
        catch (Exception e)
        {
            Log.Error("ParsedResponse", "Parse Exception: {0}", e.ToString());
            Error = new Error();
            Error.ErrorMessage = e.ToString();
            return false;
        }

        return true;
    }
}
```

The delegates become a bit simpler, e.g.
```
public delegate void OnGetModels(RESTConnector.ParsedResponse<ModelSet> resp);
```

And the response handlers become *much* simpler, e.g.
```
private void OnGetModelsResponse(RESTConnector.Request req, RESTConnector.Response resp)
{
    string customData = ((GetModelsRequest)req).Data;

    RESTConnector.ParsedResponse<ModelSet> parsedResp = new RESTConnector.ParsedResponse<ModelSet>(resp, customData, _serializer);

    if (((GetModelsRequest)req).Callback != null)
        ((GetModelsRequest)req).Callback(parsedResp);
}
```

**Comment by mediumTaj** [comment]
I think it looks good. It would be nice if we can get `HTTP Status Code` in the response as well. There are some services that only return a status code and nothing else. @ereneld what do you think?

**Comment by kimberlysiva** [comment]
I *think* we can get the status code from the `www` responseHeaders (haven't tested it yet). On that note, it'd be great to move to UnityWebRequest eventually (isn't `www` deprecated? or at least considered legacy at this point).

@mediumTaj @ereneld Let me know how you'd like to proceed, I have time to do this work today if we want to try to get it into the next release. I totally understand if it's too big a change though!

I was trying to think of other temporary ways a user could get the error codes... We could have an OnError callback, like we do for STT streaming. The problem is correlating the error with a particular request (since this is all asynchronous), but a user could provide an id in the customData field... The user code gets a bit ugly with this approach though!

**Comment by RMichaelPickering** [comment]
@kimberlysiva @mediumTaj Do any of the improvements to error handling also affect the Websocket API? There are issues lurking there in which errors or, especially, warnings from Watson are not being caught.

**Comment by kimberlysiva** [comment]
@RMichaelPickering Unfortunately not yet, that was the big TODO item. I want to set us up to return similar errors from the web socket, but I haven't delved into how that works yet.

**Comment by ereneld** [comment]
That looks good! 👍 
Using template for response object is not a bad idea (bad for compiler not for us :D ). 
Error object will hold all the information you proposed before. (error code as well - or we can implement that one eventually after this change)

Templates is a good idea and that should be the way we should proceed. Did it pass all unit tests ? with this implementation. just to make sure. 

I has the custom parsed data, and common error object and byte[] as data; so it looks like we have all things we need. 
For me; it looks pretty easy as developer. 

How about all other developers? If you look the sdk as end-user (developer); does it look easy to usage ? 
@kimberlysiva you are the implementation side; and you coded, what is your idea? Can you push your changes if not. 
@mediumTaj Can you test the changes on your end ? If all is good, then we are good to go ? 

Other suggestions ?

**Comment by mediumTaj** [comment]
@ereneld I don't think she's implemented it yet. It's a big change but it would be nice to have before asset store push.

**Comment by kimberlysiva** [comment]
@ereneld I can make this change tomorrow (it's a big one and a bit tedious, wanted it to pass review first). If we're happy with the new delegates and the generic response object then I think we can go ahead, it'll be really easy to change the details of the response object after that!

I'm currently including the JSON string in the response, because we were (sometimes) returning it in the customData field before. That means we have the same data represented three different ways (byte[], JSON string, and parsed object). This might have memory implications, so let me know if you want to get rid of any of those.

The Error is the same object as the original PR (url, error code, error message, and full server response). Some of that might be repetitive, and some we might want to promote to the response object (e.g the url field). I'm not sure if error code and HTTP status code are the same thing, do you know @mediumTaj?

I'll try to make a PR by EOD tomorrow, then we can hash out these last details! I'll be depending on you guys for unit testing.

**Comment by kimberlysiva** [comment]
@mediumTaj What's the best way to handle responses that don't have an associated object (e.g. delete requests)? My first thought is to use the same ParsedResponse with an object type:

```
public delegate void OnDeleteEnvironment(RESTConnector.ParsedResponse<object> resp);
```

`resp.DataObject` will simply be null, and the user can look at `resp.Success`

Thoughts?

**Comment by mediumTaj** [comment]
@kimberlysiva It's somewhat inconsistent between services which is why I wanted access to the http status code. Usually when there is an empty object (or in some cases nothing) returned, we at least can see success via status code. I think for now empty object is fine!

**Comment by kimberlysiva** [comment]
@mediumTaj Some of our APIs return just a string instead of json. My ParsedResponse is handling this now, and boxing that string into an object. We lose something in readability though. Take this for example (from LanguageTranslation):

```
public delegate void IdentifyCallback(string languages, RESTConnector.Error error, string customData = null);
```

becomes
```
public delegate void IdentifyCallback(RESTConnector.ParsedResponse<object> resp);
```

That object holds the languages string, but it's hard to know that. Even if it were a string instead of an object it still wouldn't have a useful name. Should we create a wrapper object for all string responses, with better naming?

Unfortunately I won't be finishing this today, there are too many edge cases like this. It's going to work well I think, we just need to work through it carefully!

**Comment by mediumTaj** [comment]
Ah, is LanguageTranslation identify operation not returning the expected object?

```
IdentifiedLanguages {
    languages (Array[IdentifiedLanguage]): A ranking of identified languages with confidence scores.
}
IdentifiedLanguage {
    language (string): The code for an identified language. ,
    confidence (number): The confidence score for the identified language.
}
```
https://watson-api-explorer.mybluemix.net/apis/language-translator-v2#!/Identify/identifyGet

No worries about not finishing today! If this works out right, I'm leaning towards a breaking change before the sdk release! Thank you for all your help!!

**Comment by kimberlysiva** [comment]
Ack, there was a commit on the 2nd that I really should have grabbed before making these changes, we have lots of conflicts... I'll look at this in a bit.

**Comment by kimberlysiva** [comment]
@mediumTaj I think this is ready for unit testing. Note that I haven't changed the Speech To Text `OnRecognize` delegates, there are a few issues with these:

1) `SpeechRecognitionEvent` doesn't have an empty constructor, so we can't use it with our current generic pattern. We parse this object much differently than all the others.
2) Streaming and Non-streaming share a delegate, we may need to break these apart.
3) I'm still not sure what we want to return for the streaming methods, but it's probably not the same ParsedResponse object.

Let me know if you have any thoughts on how to handle these. I can leave them as is for now.

**Comment by mediumTaj** [comment]
@kimberlysiva Looking good! A few things that are stopping the integration tests from passing. 

Change conversion target to answer units
Scripts/UnitTests/TestDocumentConversion.cs
```
private string _conversionTarget = ConversionTarget.Answerunits;
```

Add `Accept` header to `Identify`
Scripts/Services/LangaugeTranslator/v2/LanguageTranslator.cs
```
req.Headers["Accept"] = "application/json";
```

For Text to Speech Synthesize call, we hit line 168 in RESTConnector and get an InvalidCastException. In line 168 of RESTConnector I'm trying
```
typeof(T) == typeof(AudioClip)
{
    DataObject = (T)(object)WaveFile.ParseWAV("audioClip", Data);
}
else
{
    DataObject = (T)(object)Encoding.UTF8.GetString(Data);
}
```

Seems to work but is there a better way to do this?

**Comment by kimberlysiva** [comment]
@mediumTaj Thanks for testing!

Hmm, I'm a little concerned that `ConversionTarget.NormalizedHtml` didn't work. I don't fully understand this service, but if it worked before it should work now! I'll run a couple tests.

Adding the json header makes sense.

Oh, I see the mistake I made with the AudioClip... We could use your solution, although it doesn't set the clip name in the same way as the original. I'm trying to remember why I had `DataObject = (T)(object)Encoding.UTF8.GetString(Data);` as the fallback, we might be able to remove this.

**Comment by mediumTaj** [comment]
@kimberlysiva Yeah, if you can set the clip name that would be best!

**Comment by kimberlysiva** [comment]
@mediumTaj Try the fixes I just made. I think I prefer to let the service set the audio clip, and now the RESTConnector is no longer trying to parse the data if serializer is null and isJSON is false.

**Comment by kimberlysiva** [comment]
@mediumTaj BTW, feel free to change any of this. It's your code base, I just wanted to get things started!

**Comment by mediumTaj** [comment]
Just to get our discussion on record here:
Our team lead thinks that this may be a bad decision. The responses should not be polluted with excess data. On the other hand, if we can show this is happening in other cloud providers SDKs this might be acceptable. 

Amazon responses extend [AmazonWebServiceResponse](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/AmazonWebServiceResponse.cs). This has additional data such as StatusCode and [ResponseMetadata](https://github.com/aws/aws-sdk-net/blob/master/sdk/src/Core/Amazon.Runtime/ResponseMetadata.cs) which contains a dictionary for string metadata. I'm not sure what they put in this metadata but the response is not strictly the response from the service.

Still looking what other services do

**Comment by mediumTaj** [comment]
[Box](https://github.com/box/box-windows-sdk-v2/blob/master/Box.V2/Wrappers/BoxResponse.cs) also uses a similar pattern with their responses.

**Pull request closed without merging**
